#!/bin/sh

echo "***" >&2
echo "*** Do not use buildconf. Instead, just use: autoreconf -fi" >&2
echo "*** Doing it for you now, but buildconf may disapear in the future." >&2
echo "***" >&2

exec ${AUTORECONF:-autoreconf} -fi "${@}"
