#!/bin/sh
# Copyright (C) The libssh2 project and its contributors.
# SPDX-License-Identifier: BSD-3-Clause

echo "***" >&2
echo "*** Do not use buildconf. Instead, use: autoreconf -fi" >&2
echo "*** Doing it for you now, but buildconf may disappear in the future." >&2
echo "***" >&2

exec ${AUTORECONF:-autoreconf} -fi "${@}"
