#!/bin/sh
set -ex

MBEDTLS_SRC_ARCH=mbedtls-2.2.1

# download mbedtls sources
cd mbedtls
wget https://github.com/ARMmbed/mbedtls/archive/$MBEDTLS_SRC_ARCH.tar.gz
tar -xzf $MBEDTLS_SRC_ARCH.tar.gz

# patch mbedtls configuration
cd mbedtls-$MBEDTLS_SRC_ARCH
patch -p0 < ../mbedtls.patch

# build library
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_SHARED_MBEDTLS_LIBRARY=ON \
      -DCMAKE_INSTALL_PREFIX:PATH=../install
make install
