# Copyright (C) Alexander Lamaison <alexander.lamaison@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

# To update, get the latest digest e.g. from https://hub.docker.com/_/debian/tags
FROM debian:testing-20260824-slim@sha256:b21cba5194c0cddc19b41045ceebce11b5413ac40bac7f2410c066b5acb28091

RUN apt-get -o Dpkg::Use-Pty=0 update && \
    apt-get -o Dpkg::Use-Pty=0 install -y --no-install-suggests --no-install-recommends adduser openssh-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN [ -d /var/run/sshd ] || mkdir /var/run/sshd

# Host keys
COPY --chmod=0644 \
     ssh_host_rsa_key.pub \
     ssh_host_ecdsa_key.pub \
     ssh_host_ed25519_key.pub \
     ssh_host_mldsa44-ed25519_key.pub \
     /etc/ssh/

COPY --chmod=0600 \
     ssh_host_rsa_key \
     ssh_host_ecdsa_key \
     ssh_host_ed25519_key \
     ssh_host_mldsa44-ed25519_key \
     /etc/ssh/

# Host certificates
COPY --chmod=0644 \
     ssh_host_rsa_key-cert.pub \
     ssh_host_ecdsa_key-cert.pub \
     ssh_host_ed25519_key-cert.pub \
     ssh_host_mldsa44-ed25519_key-cert.pub \
     /etc/ssh/

# Trusted user CA keys
COPY --chmod=0600 ca_user_keys.pub /etc/ssh/

# User
RUN adduser --disabled-password --gecos 'Test user for libssh2 integration tests' libssh2
RUN echo 'libssh2:my test password' | chpasswd

# Config
RUN sed -i 's/KbdInteractiveAuthentication no/KbdInteractiveAuthentication yes/' /etc/ssh/sshd_config
COPY sshd_config /tmp/etc/ssh/
RUN cat /tmp/etc/ssh/sshd_config >> /etc/ssh/sshd_config
RUN echo 'TrustedUserCAKeys /etc/ssh/ca_user_keys.pub' >> /etc/ssh/sshd_config
RUN echo 'HostCertificate /etc/ssh/ssh_host_rsa_key-cert.pub' >> /etc/ssh/sshd_config
RUN echo 'HostCertificate /etc/ssh/ssh_host_ecdsa_key-cert.pub' >> /etc/ssh/sshd_config
RUN echo 'HostCertificate /etc/ssh/ssh_host_ed25519_key-cert.pub' >> /etc/ssh/sshd_config
RUN echo 'HostCertificate /etc/ssh/ssh_host_mldsa44-ed25519_key-cert.pub' >> /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's/session\s*required\s*pam_loginuid.so/session optional pam_loginuid.so/g' -i /etc/pam.d/sshd

USER libssh2

RUN mkdir -p /home/libssh2/.ssh

COPY --chmod=0600 --chown:libssh2:libssh2 authorized_keys /home/libssh2/.ssh/

USER root

EXPOSE 22
# -e gives logs via 'container/docker/podman logs'
CMD ["/usr/sbin/sshd", "-D", "-e"]
