.\" $Id: libssh2_sftp_open_ex.3,v 1.1 2007/02/02 16:09:12 bagder Exp $
.\"
.TH libssh2_sftp_open_ex 3 "23 Jan 2007" "libssh2 0.15" "libssh2 manual"
.SH NAME
libssh2_sftp_open - 
.SH SYNOPSIS
#include <libssh2.h>

LIBSSH2_SFTP_HANDLE *libssh2_sftp_open_ex(LIBSSH2_SFTP *sftp,
                     char *filename, int filename_len,
                     unsigned long flags, long mode, int open_type);

LIBSSH2_SFTP_HANDLE *libssh2_sftp_open(LIBSSH2_SFTP *sftp,
                     char *filename, unsigned long flags, long mode);

LIBSSH2_SFTP_HANDLE *libssh2_sftp_opendir(LIBSSH2_SFTP *sftp,
                     char *path);
.SH DESCRIPTION
    *  sftp

          SFTP instance as returned by libssh2_sftp_init(). 

    * filename

          Remote file/directory resource to open 

    * filename_len

          Length of filename 

    * flags

          Any (reasonable) combination of the LIBSSH2_FXF_* constants corresponding fopen modes. 

    * mode

          POSIX file permissions to assign if the file is being newly created. 

    * open_type

          Either of LIBSSH2_SFTP_OPENFILE (to open a file) or LIBSSH2_SFTP_OPENDIR (to open a directory). 
.SH RETURN VALUE
A pointer to the newly created LIBSSH2_SFTP_HANDLE instance or NULL on
failure.
.SH "SEE ALSO"
.BI libssh_sftp_close(3)

