.TH libssh2_channel_receive_window_adjust2 3 "26 Mar 2009" "libssh2 1.1" "libssh2 manual"
.SH NAME
libssh2_channel_receive_window_adjust2 - adjust the channel window
.SH SYNOPSIS
#include <libssh2.h>

int
libssh2_channel_receive_window_adjust2(LIBSSH2_CHANNEL * channel,
                                       unsigned long adjustment,
                                       unsigned char force,
                                       unsigned int *window);

.SH DESCRIPTION
Adjust the receive window for a channel by adjustment bytes.

The adjustment size is calculated taking into account the initial
remote window size (given when the channel was constructed), the
current remote window size and the given adjustment.

If force is false and the calculated adjustment is smaller than
LIBSSH2_CHANNEL_MINADJUST, the operation is skipped.

This function stores the new size of the receive window (as understood by
remote end) in the variable 'window' points to.

Note than in recent versions of the library, adjustment of the receive
window is done under the hood in every read operation and usage of
this function is not really required.

.SH RETURN VALUE
Return 0 on success and a negative value on error. If used in non-blocking
mode it will return LIBSSH2_ERROR_EAGAIN when it would otherwise block.
.SH ERRORS
.SH AVAILABILITY
Added in libssh2 1.1 since the previous API has deficiencies.
.SH SEE ALSO
.BR libssh2_channel_window_read_ex(3)
