.\" $Id: libssh2_trace_sethandler.3,v 1.1 2008/12/26 07:46:45 bagder Exp $
.\"
.TH libssh2_trace_sethandler 3 "03 Nov 2009" "libssh2 1.2" "libssh2 manual"
.SH NAME
libssh2_trace_sethandler - set a trace output handler
.SH SYNOPSIS
#include <libssh2.h>

typedef void (*libssh2_trace_handler_func)(LIBSSH2_SESSION*, const char*, size_t);

LIBSSH2_API int libssh2_trace_sethandler(LIBSSH2_SESSION *session, libssh2_trace_handler_func callback);

.SH DESCRIPTION
This function can be called to install a trace output handler for your application.  By default, when
tracing has been switched on via a call to libssh2_trace(), any output is written to stderr.  By calling
this method and passing a function pointer that matches the libssh2_trace_handler_func prototype, libssh2
will call back as it generates trace output.  This can be used to capture the trace output and put it into
a log file or diagnostic window.  This function has no effect unless libssh2 was built to support
this option, and a typical "release build" might not.
